Ember.Inflector.loadAll = function(){
  Ember.Inflector.plural(/$/, 's');
  Ember.Inflector.plural(/s$/i, 's');
  Ember.Inflector.plural(/^(ax|test)is$/i, '$1es');
  Ember.Inflector.plural(/(octop|vir)us$/i, '$1i');
  Ember.Inflector.plural(/(octop|vir)i$/i, '$1i');
  Ember.Inflector.plural(/(alias|status)$/i, '$1es');
  Ember.Inflector.plural(/(bu)s$/i, '$1ses');
  Ember.Inflector.plural(/(buffal|tomat)o$/i, '$1oes');
  Ember.Inflector.plural(/([ti])um$/i, '$1a');
  Ember.Inflector.plural(/([ti])a$/i, '$1a');
  Ember.Inflector.plural(/sis$/i, 'ses');
  Ember.Inflector.plural(/(?:([^f])fe|([lr])f)$/i, '$1$2ves');
  Ember.Inflector.plural(/(hive)$/i, '$1s');
  Ember.Inflector.plural(/([^aeiouy]|qu)y$/i, '$1ies');
  Ember.Inflector.plural(/(x|ch|ss|sh)$/i, '$1es');
  Ember.Inflector.plural(/(matr|vert|ind)(?:ix|ex)$/i, '$1ices');
  Ember.Inflector.plural(/^(m|l)ouse$/i, '$1ice');
  Ember.Inflector.plural(/^(m|l)ice$/i, '$1ice');
  Ember.Inflector.plural(/^(ox)$/i, '$1en');
  Ember.Inflector.plural(/^(oxen)$/i, '$1');
  Ember.Inflector.plural(/(quiz)$/i, '$1zes');

  Ember.Inflector.singular(/s$/i, '');
  Ember.Inflector.singular(/(ss)$/i, '$1');
  Ember.Inflector.singular(/(n)ews$/i, '$1ews');
  Ember.Inflector.singular(/([ti])a$/i, '$1um');
  Ember.Inflector.singular(/((a)naly|(b)a|(d)iagno|(p)arenthe|(p)rogno|(s)ynop|(t)he)(sis|ses)$/i, '$1sis');
  Ember.Inflector.singular(/(^analy)(sis|ses)$/i, '$1sis');
  Ember.Inflector.singular(/([^f])ves$/i, '$1fe');
  Ember.Inflector.singular(/(hive)s$/i, '$1');
  Ember.Inflector.singular(/(tive)s$/i, '$1');
  Ember.Inflector.singular(/([lr])ves$/i, '$1f');
  Ember.Inflector.singular(/([^aeiouy]|qu)ies$/i, '$1y');
  Ember.Inflector.singular(/(s)eries$/i, '$1eries');
  Ember.Inflector.singular(/(m)ovies$/i, '$1ovie');
  Ember.Inflector.singular(/(x|ch|ss|sh)es$/i, '$1');
  Ember.Inflector.singular(/^(m|l)ice$/i, '$1ouse');
  Ember.Inflector.singular(/(bus)(es)?$/i, '$1');
  Ember.Inflector.singular(/(o)es$/i, '$1');
  Ember.Inflector.singular(/(shoe)s$/i, '$1');
  Ember.Inflector.singular(/(cris|test)(is|es)$/i, '$1is');
  Ember.Inflector.singular(/^(a)x[ie]s$/i, '$1xis');
  Ember.Inflector.singular(/(octop|vir)(us|i)$/i, '$1us');
  Ember.Inflector.singular(/(alias|status)(es)?$/i, '$1');
  Ember.Inflector.singular(/^(ox)en/i, '$1');
  Ember.Inflector.singular(/(vert|ind)ices$/i, '$1ex');
  Ember.Inflector.singular(/(matr)ices$/i, '$1ix');
  Ember.Inflector.singular(/(quiz)zes$/i, '$1');
  Ember.Inflector.singular(/(database)s$/i, '$1');

  Ember.Inflector.irregular('person', 'people');
  Ember.Inflector.irregular('man', 'men');
  Ember.Inflector.irregular('child', 'children');
  Ember.Inflector.irregular('sex', 'sexes');
  Ember.Inflector.irregular('move', 'moves');
  Ember.Inflector.irregular('cow', 'kine');
  Ember.Inflector.irregular('zombie', 'zombies');

  Ember.Inflector.uncountable("equipment information rice money species series fish sheep jeans police".w());
};
