---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install

stages:
  - test
  - additional tests
  - node tests
  - versioned tests

script:
  - yarn lint:js
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup

jobs:
  fail_fast: true

  include:
    - stage: test
      env: NAME=test
      script: yarn test

    - stage: additional tests
      env: NAME=floating dependencies
      install: yarn install --no-lockfile --non-interactive
      script: yarn test

    - stage: node tests
      node_js: "8"
      env: NAME=node tests
      script: yarn test:node

    - stage: versioned tests
      env: EMBER_TRY_SCENARIO=ember-lts-2.12
    - env: EMBER_TRY_SCENARIO=ember-lts-2.16
    - env: EMBER_TRY_SCENARIO=ember-lts-2.18
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default

  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
